# -*- coding: utf-8 -*-
"""Plaatsen waarvoor Den Dekker Dakbedekking een eigen pagina heeft (dakdekker-<slug>)."""

# slug, naam, provincie, regio, kenmerk
PLAATSEN = [
    # ------------------------------------------------ Noord-Brabant
    ("bergen-op-zoom", "Bergen op Zoom", "Noord-Brabant", "West-Brabant",
     "De historische binnenstad heeft smalle panden met steile pannendaken en gemetselde schoorstenen; daarbuiten liggen naoorlogse wijken met rijwoningen."),
    ("roosendaal", "Roosendaal", "Noord-Brabant", "West-Brabant",
     "Roosendaal groeide sterk in de jaren zestig en zeventig, waardoor veel daken nu tegelijk de vervangingsleeftijd naderen."),
    ("etten-leur", "Etten-Leur", "Noord-Brabant", "West-Brabant",
     "Grote uitbreidingswijken uit de jaren zeventig en tachtig met veel rijwoningen met een flauw hellend dak en een platte aanbouw."),
    ("steenbergen", "Steenbergen", "Noord-Brabant", "West-Brabant",
     "Steenbergen ligt in het open poldergebied, wat de windbelasting op nokvorsten, gevelpannen en dakranden verhoogt."),
    ("rucphen", "Rucphen", "Noord-Brabant", "West-Brabant",
     "Rucphen bestaat uit vijf dorpskernen met veel vrijstaande en halfopen woningen, en daarnaast recreatiewoningen op de zandgronden."),
    ("zundert", "Zundert", "Noord-Brabant", "West-Brabant",
     "Zundert is een boomkwekersgemeente; veel bijgebouwen en loodsen hebben golfplaten daken uit de periode voor 2001."),
    ("hoogerheide", "Hoogerheide", "Noord-Brabant", "West-Brabant",
     "Hoogerheide ligt in de gemeente Woensdrecht op de rand van de Brabantse Wal, met veel naoorlogse eengezinswoningen."),
    ("baarle-nassau", "Baarle-Nassau", "Noord-Brabant", "Baronie",
     "Baarle-Nassau is verweven met het Belgische Baarle-Hertog, wat betekent dat vergunningsregels per perceel kunnen verschillen."),
    ("breda", "Breda", "Noord-Brabant", "Baronie",
     "Breda combineert een beschermde binnenstad met vooroorlogse wijken en grote naoorlogse uitbreidingen; in het centrum gelden erfgoedregels bij dakwijzigingen."),
    ("oosterhout", "Oosterhout", "Noord-Brabant", "Baronie",
     "Oosterhout heeft een oude kern met gesloten bebouwing en daaromheen woonwijken uit de jaren zestig tot tachtig."),
    ("geertruidenberg", "Geertruidenberg", "Noord-Brabant", "Baronie",
     "De vestingkern telt monumenten waarvoor bij dakwerk aanvullende regels gelden; daarbuiten overheerst naoorlogse bebouwing."),
    ("made", "Made", "Noord-Brabant", "Baronie",
     "Made ligt in de gemeente Drimmelen, met een landelijke omgeving en veel vrijstaande woningen en agrarische bijgebouwen."),
    ("zevenbergen", "Zevenbergen", "Noord-Brabant", "West-Brabant",
     "Zevenbergen hoort bij de gemeente Moerdijk en ligt in open polderland, waar wind vrij spel heeft op de dakranden."),
    ("dongen", "Dongen", "Noord-Brabant", "Langstraat",
     "Dongen heeft een leerindustrieverleden met arbeiderswoningen uit het interbellum en latere uitbreidingswijken."),
    ("rijen", "Rijen", "Noord-Brabant", "Langstraat",
     "Rijen hoort bij de gemeente Gilze en Rijen en groeide vooral na de oorlog, met veel rijwoningen met een zadeldak."),
    ("goirle", "Goirle", "Noord-Brabant", "Hart van Brabant",
     "Goirle grenst direct aan Tilburg en bestaat grotendeels uit naoorlogse woonwijken met eengezinswoningen."),
    ("tilburg", "Tilburg", "Noord-Brabant", "Hart van Brabant",
     "Tilburg heeft veel vooroorlogse arbeiderswoningen met smalle dakvlakken, naast grootschalige naoorlogse wijken."),
    ("oisterwijk", "Oisterwijk", "Noord-Brabant", "Hart van Brabant",
     "Oisterwijk ligt tussen bos en vennen; veel villa's staan onder hoge bomen, wat bladophoping in de goot versterkt."),
    ("loon-op-zand", "Loon op Zand", "Noord-Brabant", "Langstraat",
     "Loon op Zand ligt tussen bos en duinen, met veel vrijstaande woningen en recreatiewoningen met platte daken."),
    ("kaatsheuvel", "Kaatsheuvel", "Noord-Brabant", "Langstraat",
     "Kaatsheuvel hoort bij de gemeente Loon op Zand en heeft grote uitbreidingswijken uit de jaren zeventig en tachtig."),
    ("waalwijk", "Waalwijk", "Noord-Brabant", "Langstraat",
     "Waalwijk kent een schoen- en lederverleden met bedrijfspanden en woningen uit het interbellum, en platte daken op de bedrijventerreinen."),
    ("drunen", "Drunen", "Noord-Brabant", "Langstraat",
     "Drunen hoort bij de gemeente Heusden en groeide vooral na 1960, met veel eengezinswoningen met pannendaken."),
    ("vlijmen", "Vlijmen", "Noord-Brabant", "Langstraat",
     "Vlijmen hoort eveneens bij de gemeente Heusden en heeft naoorlogse woonwijken met een oude dorpskern in het midden."),
    ("heusden", "Heusden", "Noord-Brabant", "Langstraat",
     "De vesting Heusden is een beschermd stadsgezicht; voor dakwerken aan panden binnen de vesting gelden aanvullende regels."),
    ("den-bosch", "Den Bosch", "Noord-Brabant", "Meierij",
     "De binnenstad van Den Bosch bestaat uit diepe panden met steile daken en veel schoorstenen; erfgoedregels zijn er eerder regel dan uitzondering."),
    ("rosmalen", "Rosmalen", "Noord-Brabant", "Meierij",
     "Rosmalen hoort bij de gemeente 's-Hertogenbosch en bestaat overwegend uit naoorlogse woonwijken."),
    ("vught", "Vught", "Noord-Brabant", "Meierij",
     "Vught telt veel villabebouwing uit het interbellum met complexe dakvormen, kilgoten en dakkapellen."),
    ("boxtel", "Boxtel", "Noord-Brabant", "Meierij",
     "Boxtel heeft een dorpskern met gesloten bebouwing en daaromheen naoorlogse uitbreidingen aan weerszijden van de Dommel."),
    ("sint-michielsgestel", "Sint-Michielsgestel", "Noord-Brabant", "Meierij",
     "Sint-Michielsgestel ligt aan de Dommel en heeft veel vrijstaande woningen op ruime percelen."),
    ("schijndel", "Schijndel", "Noord-Brabant", "Meierij",
     "Schijndel hoort bij de gemeente Meierijstad en bestaat uit een langgerekte kern met lintbebouwing langs de uitvalswegen."),
    ("sint-oedenrode", "Sint-Oedenrode", "Noord-Brabant", "Meierij",
     "Sint-Oedenrode heeft een historische kern en daaromheen naoorlogse wijken en agrarische bebouwing."),
    ("veghel", "Veghel", "Noord-Brabant", "Meierij",
     "Veghel combineert woonwijken met grote bedrijfspanden waarvan de platte daken een eigen onderhoudsritme vragen."),
    ("uden", "Uden", "Noord-Brabant", "Maashorst",
     "Uden groeide sterk na 1960; veel woningen hebben een eerste generatie dakbedekking die nu vervangen wordt."),
    ("heesch", "Heesch", "Noord-Brabant", "Maashorst",
     "Heesch hoort bij de gemeente Bernheze en bestaat uit een dorpskern met daaromheen verkavelingen uit de jaren zeventig."),
    ("oss", "Oss", "Noord-Brabant", "Maasland",
     "Oss heeft een industrieel verleden met arbeiderswijken uit het interbellum naast grootschalige naoorlogse uitbreidingen."),
    ("grave", "Grave", "Noord-Brabant", "Land van Cuijk",
     "Grave is een vestingstad aan de Maas met een beschermd stadsgezicht en steile pannendaken in de kern."),
    ("cuijk", "Cuijk", "Noord-Brabant", "Land van Cuijk",
     "Cuijk ligt aan de Maas en heeft naast de kern veel naoorlogse woonwijken met eengezinswoningen."),
    ("boxmeer", "Boxmeer", "Noord-Brabant", "Land van Cuijk",
     "Boxmeer is het grootste centrum van het Land van Cuijk, met een dorpskern en uitbreidingswijken uit meerdere periodes."),
    ("beugen", "Beugen", "Noord-Brabant", "Land van Cuijk",
     "Beugen is een klein kerkdorp aan de Maas met veel vrijstaande woningen en agrarische bijgebouwen."),
    ("gemert", "Gemert", "Noord-Brabant", "Peel",
     "Gemert heeft een historische kern rond het kasteel en daaromheen naoorlogse woonwijken en boerderijen."),
    ("deurne", "Deurne", "Noord-Brabant", "Peel",
     "Deurne ligt in de Peel, met veel losse boerderijen en schuren waarvan de daken uit de periode voor 2001 dateren."),
    ("asten", "Asten", "Noord-Brabant", "Peel",
     "Asten is een landelijke gemeente met veel agrarische bebouwing naast de dorpskern."),
    ("someren", "Someren", "Noord-Brabant", "Peel",
     "Someren bestaat uit vier kernen met overwegend open bebouwing en veel bijgebouwen."),
    ("helmond", "Helmond", "Noord-Brabant", "Peel",
     "Helmond heeft grote naoorlogse wijken naast vooroorlogse arbeiderswoningen met smalle, steile dakvlakken."),
    ("mierlo", "Mierlo", "Noord-Brabant", "Peel",
     "Mierlo hoort bij de gemeente Geldrop-Mierlo en bestaat grotendeels uit naoorlogse eengezinswoningen."),
    ("geldrop", "Geldrop", "Noord-Brabant", "Zuidoost-Brabant",
     "Geldrop heeft een textielverleden met arbeiderswoningen uit het interbellum en latere uitbreidingswijken."),
    ("nuenen", "Nuenen", "Noord-Brabant", "Zuidoost-Brabant",
     "Nuenen telt veel vrijstaande woningen op ruime, bosrijke percelen, wat de gootbelasting in de herfst verhoogt."),
    ("eindhoven", "Eindhoven", "Noord-Brabant", "Zuidoost-Brabant",
     "Eindhoven bestaat voor een groot deel uit woningen uit de periode 1920 tot 1970, waaronder veel voormalige bedrijfswoningen met eenvoudige zadeldaken."),
    ("best", "Best", "Noord-Brabant", "Zuidoost-Brabant",
     "Best groeide vooral na 1960 en heeft veel rijwoningen met een pannendak en een platte uitbouw achteraan."),
    ("son-en-breugel", "Son en Breugel", "Noord-Brabant", "Zuidoost-Brabant",
     "Son en Breugel bestaat uit twee kernen aan het Wilhelminakanaal met veel groen rond de woningen."),
    ("veldhoven", "Veldhoven", "Noord-Brabant", "Zuidoost-Brabant",
     "Veldhoven ontstond uit vier dorpen en groeide na 1960 sterk, met veel eengezinswoningen uit dezelfde bouwperiode."),
    ("waalre", "Waalre", "Noord-Brabant", "Zuidoost-Brabant",
     "Waalre heeft veel vrijstaande woningen tussen bos en heide, met complexe dakvormen en dakkapellen."),
    ("valkenswaard", "Valkenswaard", "Noord-Brabant", "Zuidoost-Brabant",
     "Valkenswaard ligt tussen bos en beekdalen en telt naast de kern veel vrijstaande woningen op ruime kavels."),
    ("bergeijk", "Bergeijk", "Noord-Brabant", "Kempen",
     "Bergeijk bestaat uit vier kernen in de Brabantse Kempen, met veel langgevelboerderijen en open bebouwing."),
    ("eersel", "Eersel", "Noord-Brabant", "Kempen",
     "Eersel heeft een historische dorpskern en daaromheen landelijke bebouwing met grote dakvlakken."),
    ("bladel", "Bladel", "Noord-Brabant", "Kempen",
     "Bladel bestaat uit vijf kernen met overwegend open bebouwing en veel agrarische bijgebouwen."),
    ("reusel", "Reusel", "Noord-Brabant", "Kempen",
     "Reusel ligt aan de Belgische grens en heeft een landelijk karakter met veel losse hoeves en loodsen."),
    ("budel", "Budel", "Noord-Brabant", "Kempen",
     "Budel hoort bij de gemeente Cranendonck, tegen de Belgische grens, met een landelijke omgeving en veel bijgebouwen."),
    ("werkendam", "Werkendam", "Noord-Brabant", "Altena",
     "Werkendam ligt aan de Biesbosch in open rivierenland, waar wind en vocht de dakranden extra belasten."),
    ("zaltbommel", "Zaltbommel", "Gelderland", "Bommelerwaard",
     "Zaltbommel heeft een beschermde vestingkern met steile daken en daarbuiten naoorlogse uitbreidingen."),

    # ------------------------------------------------ Limburg
    ("weert", "Weert", "Limburg", "Midden-Limburg",
     "Weert heeft een compact centrum met gesloten bebouwing en daaromheen naoorlogse wijken en landelijk gebied."),
    ("nederweert", "Nederweert", "Limburg", "Midden-Limburg",
     "Nederweert is een landelijke gemeente met veel agrarische bebouwing en losse schuren met golfplaten daken."),
    ("venray", "Venray", "Limburg", "Noord-Limburg",
     "Venray bestaat uit een centrale kern met dertien kerkdorpen eromheen, met veel vrijstaande en agrarische bebouwing."),
    ("horst", "Horst", "Limburg", "Noord-Limburg",
     "Horst aan de Maas is sterk agrarisch, met veel kassen, loodsen en bijgebouwen naast de woningen."),
    ("gennep", "Gennep", "Limburg", "Noord-Limburg",
     "Gennep ligt op de grens van Limburg en Gelderland aan de Maas, met een historische kern en naoorlogse uitbreidingen."),
    ("maastricht", "Maastricht", "Limburg", "Heuvelland",
     "Maastricht heeft een grote historische binnenstad met leien en pannen op steile daken, waar erfgoedregels vrijwel altijd meespelen."),

    # ------------------------------------------------ Gelderland
    ("nijmegen", "Nijmegen", "Gelderland", "Rijk van Nijmegen",
     "Nijmegen heeft vooroorlogse wijken met steile daken en dakkapellen, naast naoorlogse wederopbouwbouw in het centrum."),
    ("groesbeek", "Groesbeek", "Gelderland", "Rijk van Nijmegen",
     "Groesbeek ligt in heuvelachtig, bosrijk gebied; hoge bomen rond de woningen vragen frequenter gootonderhoud."),
    ("wijchen", "Wijchen", "Gelderland", "Rijk van Nijmegen",
     "Wijchen groeide sterk na 1960 en heeft veel eengezinswoningen met een eerste generatie dakbedekking."),
    ("beuningen", "Beuningen", "Gelderland", "Rijk van Nijmegen",
     "Beuningen ligt aan de Waal in open rivierenland, met naoorlogse woonwijken rond de oude dorpskern."),
    ("druten", "Druten", "Gelderland", "Rivierenland",
     "Druten ligt in het Land van Maas en Waal, met dijkwoningen en veel open bebouwing in het buitengebied."),
    ("arnhem", "Arnhem", "Gelderland", "Veluwezoom",
     "Arnhem heeft villawijken op de stuwwal met complexe dakvormen, naast wederopbouwbouw in het centrum."),
    ("velp", "Velp", "Gelderland", "Veluwezoom",
     "Velp hoort bij de gemeente Rheden en telt veel grote woningen uit het interbellum met kilgoten en dakkapellen."),
    ("oosterbeek", "Oosterbeek", "Gelderland", "Veluwezoom",
     "Oosterbeek ligt in de gemeente Renkum tussen bos en uiterwaarden, met veel villabebouwing onder hoge bomen."),
    ("westervoort", "Westervoort", "Gelderland", "Liemers",
     "Westervoort bestaat vrijwel volledig uit naoorlogse woonwijken, met veel woningen uit dezelfde bouwperiode."),
    ("duiven", "Duiven", "Gelderland", "Liemers",
     "Duiven groeide sterk in de jaren zeventig en tachtig, waardoor de daken er grotendeels van gelijke leeftijd zijn."),
    ("zevenaar", "Zevenaar", "Gelderland", "Liemers",
     "Zevenaar heeft een oude kern met gesloten bebouwing en daaromheen uitbreidingswijken uit meerdere periodes."),
    ("elst", "Elst", "Gelderland", "Betuwe",
     "Elst hoort bij de gemeente Overbetuwe en ligt in open rivierenland tussen Arnhem en Nijmegen."),
    ("bemmel", "Bemmel", "Gelderland", "Betuwe",
     "Bemmel hoort bij de gemeente Lingewaard en heeft naast de dorpskern veel boomgaarden en agrarische bebouwing."),
    ("tiel", "Tiel", "Gelderland", "Betuwe",
     "Tiel ligt aan de Waal met een historische kern en daarbuiten naoorlogse wijken en bedrijventerreinen."),
    ("geldermalsen", "Geldermalsen", "Gelderland", "Betuwe",
     "Geldermalsen hoort bij de gemeente West Betuwe, met veel lintbebouwing langs dijken en wegen."),
    ("culemborg", "Culemborg", "Gelderland", "Betuwe",
     "Culemborg heeft een beschermde binnenstad met steile daken en daarbuiten grote naoorlogse uitbreidingen."),
    ("apeldoorn", "Apeldoorn", "Gelderland", "Veluwe",
     "Apeldoorn telt veel vrijstaande woningen tussen naaldbomen, waardoor naalden in de goot een terugkerend punt zijn."),
    ("barneveld", "Barneveld", "Gelderland", "Veluwe",
     "Barneveld is sterk agrarisch, met veel stallen en loodsen naast de woonbebouwing."),
    ("nijkerk", "Nijkerk", "Gelderland", "Veluwe",
     "Nijkerk ligt aan de rand van de Veluwe bij het Nijkerkernauw, met een oude kern en nieuwere woonwijken."),
    ("putten", "Putten", "Gelderland", "Veluwe",
     "Putten heeft een landelijk karakter met veel vrijstaande woningen en recreatiebebouwing op de zandgronden."),
    ("ermelo", "Ermelo", "Gelderland", "Veluwe",
     "Ermelo ligt tussen bos en heide, met veel bungalows en recreatiewoningen met flauw hellende daken."),
    ("harderwijk", "Harderwijk", "Gelderland", "Veluwe",
     "Harderwijk heeft een historische binnenstad aan het water en daarbuiten naoorlogse wijken."),
    ("nunspeet", "Nunspeet", "Gelderland", "Veluwe",
     "Nunspeet ligt in bosrijk gebied met veel vrijstaande woningen en vakantieparken."),
    ("ede", "Ede", "Gelderland", "Veluwe",
     "Ede combineert een grote kern met dorpen in het buitengebied en veel naoorlogse woningbouw."),
    ("wageningen", "Wageningen", "Gelderland", "Veluwe",
     "Wageningen heeft een compacte kern met wederopbouwbouw en daarbuiten wijken uit de jaren zestig en zeventig."),

    # ------------------------------------------------ Utrecht
    ("utrecht", "Utrecht", "Utrecht", "Stad Utrecht",
     "De Utrechtse binnenstad bestaat uit diepe panden met steile daken en veel schoorstenen; in de negentiende-eeuwse wijken liggen smalle dakvlakken op rijwoningen."),
    ("vleuten", "Vleuten", "Utrecht", "Stad Utrecht",
     "Vleuten hoort bij de gemeente Utrecht en ligt naast Leidsche Rijn, met veel nieuwbouw naast een oude dorpskern."),
    ("nieuwegein", "Nieuwegein", "Utrecht", "Stadsregio Utrecht",
     "Nieuwegein is grotendeels gebouwd in de jaren zeventig en tachtig, waardoor de daken er grotendeels van gelijke leeftijd zijn."),
    ("ijsselstein", "IJsselstein", "Utrecht", "Lopikerwaard",
     "IJsselstein heeft een historische kern met daaromheen grote uitbreidingswijken uit de jaren zeventig en tachtig."),
    ("houten", "Houten", "Utrecht", "Kromme Rijnstreek",
     "Houten groeide vanaf de jaren zeventig van dorp naar groeikern, met veel woningen uit dezelfde bouwperiode."),
    ("wijk-bij-duurstede", "Wijk bij Duurstede", "Utrecht", "Kromme Rijnstreek",
     "Wijk bij Duurstede heeft een beschermde kern aan de Lek en daarbuiten naoorlogse woonwijken."),
    ("zeist", "Zeist", "Utrecht", "Utrechtse Heuvelrug",
     "Zeist telt veel villabebouwing uit het interbellum met complexe dakvormen, kilgoten en zinken goten."),
    ("driebergen", "Driebergen", "Utrecht", "Utrechtse Heuvelrug",
     "Driebergen ligt in de gemeente Utrechtse Heuvelrug, met veel grote woningen onder hoge bomen."),
    ("doorn", "Doorn", "Utrecht", "Utrechtse Heuvelrug",
     "Doorn heeft veel landhuizen en villa's op ruime, bosrijke percelen, met complexe daken en veel dakdoorvoeren."),
    ("bilthoven", "Bilthoven", "Utrecht", "Utrechtse Heuvelrug",
     "Bilthoven hoort bij De Bilt en bestaat grotendeels uit villabebouwing tussen naaldbomen."),
    ("amersfoort", "Amersfoort", "Utrecht", "Eemland",
     "Amersfoort heeft een beschermde binnenstad met steile daken naast grote uitbreidingswijken uit de jaren tachtig en negentig."),
    ("leusden", "Leusden", "Utrecht", "Eemland",
     "Leusden is grotendeels na 1970 gebouwd, met veel eengezinswoningen met pannendaken en platte aanbouwen."),
    ("soest", "Soest", "Utrecht", "Eemland",
     "Soest ligt tussen bos en heide met veel vrijstaande woningen en bungalows uit de jaren zestig."),
    ("baarn", "Baarn", "Utrecht", "Eemland",
     "Baarn telt veel monumentale villa's met leien en zinken dakdetails, waarvoor bij dakwerk aanvullende regels gelden."),
    ("bunschoten", "Bunschoten", "Utrecht", "Eemland",
     "Bunschoten-Spakenburg ligt aan het Eemmeer, waar open ligging en vochtige lucht de dakranden extra belasten."),
    ("veenendaal", "Veenendaal", "Utrecht", "Gelderse Vallei",
     "Veenendaal groeide sterk na 1960 en heeft veel rijwoningen met een eenvoudig zadeldak."),
    ("rhenen", "Rhenen", "Utrecht", "Gelderse Vallei",
     "Rhenen ligt op de Utrechtse Heuvelrug aan de Rijn, met wederopbouwbouw in de kern en villa's op de helling."),
    ("woerden", "Woerden", "Utrecht", "Groene Hart",
     "Woerden heeft een historische kern binnen de gracht en daarbuiten woonwijken uit de jaren zestig tot negentig."),
    ("montfoort", "Montfoort", "Utrecht", "Groene Hart",
     "Montfoort is een kleine historische stad met beschermde bebouwing in de kern en nieuwere wijken eromheen."),
    ("oudewater", "Oudewater", "Utrecht", "Groene Hart",
     "Oudewater heeft een beschermd stadsgezicht met smalle panden en steile daken langs de IJssel."),
    ("maarssen", "Maarssen", "Utrecht", "Vechtstreek",
     "Maarssen hoort bij Stichtse Vecht en telt buitenplaatsen langs de Vecht naast naoorlogse woonwijken."),
    ("breukelen", "Breukelen", "Utrecht", "Vechtstreek",
     "Breukelen ligt aan de Vecht met historische buitenplaatsen en een dorpskern met gesloten bebouwing."),
    ("abcoude", "Abcoude", "Utrecht", "Vechtstreek",
     "Abcoude hoort bij De Ronde Venen en heeft een oude dorpskern in open, waterrijk veenweidegebied."),
    ("mijdrecht", "Mijdrecht", "Utrecht", "Vechtstreek",
     "Mijdrecht ligt in het veenweidegebied van De Ronde Venen, met overwegend naoorlogse bebouwing."),
    ("vianen", "Vianen", "Utrecht", "Vijfheerenlanden",
     "Vianen heeft een historische kern aan de Lek en daarbuiten naoorlogse wijken en bedrijventerreinen."),
    ("leerdam", "Leerdam", "Utrecht", "Vijfheerenlanden",
     "Leerdam ligt aan de Linge en hoort sinds 2019 bij de provincie Utrecht; de kern heeft veel vooroorlogse bebouwing."),

    # ------------------------------------------------ Zuid-Holland
    ("rotterdam", "Rotterdam", "Zuid-Holland", "Rijnmond",
     "Rotterdam heeft veel naoorlogse bouw met platte daken, naast vooroorlogse wijken met hellende voordaken en platte achteraanbouwen."),
    ("schiedam", "Schiedam", "Zuid-Holland", "Rijnmond",
     "Schiedam heeft een historische binnenstad met smalle panden en steile daken, naast naoorlogse hoogbouw."),
    ("vlaardingen", "Vlaardingen", "Zuid-Holland", "Rijnmond",
     "Vlaardingen ligt aan de Nieuwe Maas met veel wederopbouwwijken uit de jaren vijftig en zestig."),
    ("maassluis", "Maassluis", "Zuid-Holland", "Rijnmond",
     "Maassluis heeft een historische kern aan het water en daarbuiten naoorlogse wijken met platte daken."),
    ("capelle-aan-den-ijssel", "Capelle aan den IJssel", "Zuid-Holland", "Rijnmond",
     "Capelle aan den IJssel is grotendeels na 1960 gebouwd, met veel gestapelde bouw en platte daken."),
    ("krimpen-aan-den-ijssel", "Krimpen aan den IJssel", "Zuid-Holland", "Krimpenerwaard",
     "Krimpen aan den IJssel groeide sterk na 1960, met veel eengezinswoningen van gelijke leeftijd."),
    ("schoonhoven", "Schoonhoven", "Zuid-Holland", "Krimpenerwaard",
     "Schoonhoven heeft een beschermd stadsgezicht met steile daken en gemetselde schoorstenen in de kern."),
    ("nieuwerkerk-aan-den-ijssel", "Nieuwerkerk aan den IJssel", "Zuid-Holland", "Zuidplas",
     "Nieuwerkerk aan den IJssel ligt in de diepste polder van Nederland en bestaat vooral uit naoorlogse woonwijken."),
    ("barendrecht", "Barendrecht", "Zuid-Holland", "IJsselmonde",
     "Barendrecht groeide sterk vanaf de jaren tachtig, met veel rijwoningen met pannendaken en dakkapellen."),
    ("ridderkerk", "Ridderkerk", "Zuid-Holland", "IJsselmonde",
     "Ridderkerk heeft naoorlogse wijken rond een oude dorpskern, met veel eengezinswoningen."),
    ("zwijndrecht", "Zwijndrecht", "Zuid-Holland", "Drechtsteden",
     "Zwijndrecht ligt tegenover Dordrecht aan de Oude Maas, met wederopbouwbouw en latere uitbreidingen."),
    ("dordrecht", "Dordrecht", "Zuid-Holland", "Drechtsteden",
     "Dordrecht heeft de grootste historische binnenstad van de regio, met diepe panden, steile daken en veel schoorstenen."),
    ("papendrecht", "Papendrecht", "Zuid-Holland", "Drechtsteden",
     "Papendrecht is grotendeels na 1960 gebouwd, met veel woningen van gelijke leeftijd en platte aanbouwen."),
    ("sliedrecht", "Sliedrecht", "Zuid-Holland", "Drechtsteden",
     "Sliedrecht is langgerekt langs de Merwede gebouwd, met lintbebouwing en naoorlogse wijken erachter."),
    ("hendrik-ido-ambacht", "Hendrik-Ido-Ambacht", "Zuid-Holland", "Drechtsteden",
     "Hendrik-Ido-Ambacht groeide sterk vanaf de jaren zeventig, met veel eengezinswoningen met zadeldaken."),
    ("alblasserdam", "Alblasserdam", "Zuid-Holland", "Drechtsteden",
     "Alblasserdam ligt aan de Noord, met een dorpskern langs het water en naoorlogse wijken erachter."),
    ("hardinxveld-giessendam", "Hardinxveld-Giessendam", "Zuid-Holland", "Alblasserwaard",
     "Hardinxveld-Giessendam bestaat uit langgerekte lintbebouwing langs de Merwede met woonwijken erachter."),
    ("gorinchem", "Gorinchem", "Zuid-Holland", "Alblasserwaard",
     "Gorinchem heeft een vestingkern met beschermde bebouwing en daarbuiten naoorlogse uitbreidingen."),
    ("oud-beijerland", "Oud-Beijerland", "Zuid-Holland", "Hoeksche Waard",
     "Oud-Beijerland ligt in open polderland, waar wind vrij spel heeft op nokvorsten en dakranden."),
    ("spijkenisse", "Spijkenisse", "Zuid-Holland", "Voorne-Putten",
     "Spijkenisse groeide vanaf de jaren zestig van dorp naar stad, met veel woningen uit dezelfde periode."),
    ("hellevoetsluis", "Hellevoetsluis", "Zuid-Holland", "Voorne-Putten",
     "Hellevoetsluis heeft een vestingkern en ligt dicht bij zee, wat de belasting op zink- en loodwerk verhoogt."),
    ("brielle", "Brielle", "Zuid-Holland", "Voorne-Putten",
     "Brielle is een vestingstad met een beschermd stadsgezicht en steile pannendaken in de kern."),
    ("delft", "Delft", "Zuid-Holland", "Haaglanden",
     "Delft heeft een beschermde binnenstad met diepe panden, steile daken en veel schoorstenen en dakkapellen."),
    ("den-haag", "Den Haag", "Zuid-Holland", "Haaglanden",
     "Den Haag heeft veel vooroorlogse etagebouw met hellende voordaken en platte achterdaken, en dicht bij zee extra belasting op zinkwerk."),
    ("rijswijk", "Rijswijk", "Zuid-Holland", "Haaglanden",
     "Rijswijk bestaat grotendeels uit wederopbouwbouw en latere uitbreidingen, met veel platte daken."),
    ("voorburg", "Voorburg", "Zuid-Holland", "Haaglanden",
     "Voorburg heeft een oude kern met monumenten naast woonwijken uit het interbellum en de jaren zestig."),
    ("leidschendam", "Leidschendam", "Zuid-Holland", "Haaglanden",
     "Leidschendam groeide vooral na de oorlog, met veel eengezinswoningen en gestapelde bouw met platte daken."),
    ("zoetermeer", "Zoetermeer", "Zuid-Holland", "Haaglanden",
     "Zoetermeer is grotendeels tussen 1965 en 1995 gebouwd, waardoor grote aantallen daken tegelijk de vervangingsleeftijd naderen."),
    ("pijnacker", "Pijnacker", "Zuid-Holland", "Haaglanden",
     "Pijnacker hoort bij Pijnacker-Nootdorp, met een oude kern en veel nieuwbouw uit de jaren negentig en later."),
    ("bergschenhoek", "Bergschenhoek", "Zuid-Holland", "Lansingerland",
     "Bergschenhoek hoort bij Lansingerland en bestaat overwegend uit nieuwere woonwijken met pannendaken."),
    ("berkel-en-rodenrijs", "Berkel en Rodenrijs", "Zuid-Holland", "Lansingerland",
     "Berkel en Rodenrijs ligt in glastuinbouwgebied, met kassen en bedrijfsgebouwen naast de woonbebouwing."),
    ("naaldwijk", "Naaldwijk", "Zuid-Holland", "Westland",
     "Naaldwijk ligt midden in het Westlandse glastuinbouwgebied, met veel bedrijfsdaken naast woningbouw."),
    ("monster", "Monster", "Zuid-Holland", "Westland",
     "Monster ligt vlak achter de duinen; zoute lucht en wind belasten zink- en loodwerk sterker dan in het binnenland."),
    ("wassenaar", "Wassenaar", "Zuid-Holland", "Duin- en Bollenstreek",
     "Wassenaar telt veel landhuizen en villa's met leien, rieten en complexe pannendaken onder hoge bomen."),
    ("voorschoten", "Voorschoten", "Zuid-Holland", "Duin- en Bollenstreek",
     "Voorschoten heeft een oude dorpskern met daaromheen villabebouwing en naoorlogse wijken."),
    ("leiden", "Leiden", "Zuid-Holland", "Duin- en Bollenstreek",
     "Leiden heeft een grote historische binnenstad met smalle panden, steile daken en veel schoorstenen."),
    ("katwijk", "Katwijk", "Zuid-Holland", "Duin- en Bollenstreek",
     "Katwijk ligt aan zee, waar zout en wind de dakranden, het zinkwerk en de bevestiging van pannen extra belasten."),
    ("noordwijk", "Noordwijk", "Zuid-Holland", "Duin- en Bollenstreek",
     "Noordwijk ligt direct achter de duinen, met naast woningbouw veel hotel- en recreatiebebouwing met platte daken."),
    ("sassenheim", "Sassenheim", "Zuid-Holland", "Duin- en Bollenstreek",
     "Sassenheim hoort bij Teylingen en ligt in de bollenstreek, met een dorpskern en naoorlogse uitbreidingen."),
    ("lisse", "Lisse", "Zuid-Holland", "Duin- en Bollenstreek",
     "Lisse ligt in het bollengebied met een langgerekte kern en veel bedrijfsbebouwing in het buitengebied."),
    ("hillegom", "Hillegom", "Zuid-Holland", "Duin- en Bollenstreek",
     "Hillegom heeft een dorpskern met gesloten bebouwing en daaromheen woonwijken uit meerdere periodes."),
    ("alphen-aan-den-rijn", "Alphen aan den Rijn", "Zuid-Holland", "Groene Hart",
     "Alphen aan den Rijn groeide sterk na 1960 en ligt in veenweidegebied, waar bodemdaling de constructie kan belasten."),
    ("boskoop", "Boskoop", "Zuid-Holland", "Groene Hart",
     "Boskoop hoort bij Alphen aan den Rijn en is een boomkwekersdorp met veel bijgebouwen en kassen."),
    ("bodegraven", "Bodegraven", "Zuid-Holland", "Groene Hart",
     "Bodegraven ligt aan de Oude Rijn in veenweidegebied, met lintbebouwing en naoorlogse wijken."),
    ("waddinxveen", "Waddinxveen", "Zuid-Holland", "Groene Hart",
     "Waddinxveen bestaat grotendeels uit naoorlogse woonwijken in polder- en veengebied."),
    ("gouda", "Gouda", "Zuid-Holland", "Groene Hart",
     "Gouda heeft een beschermde binnenstad met smalle panden en steile daken; in de veenbodem speelt verzakking mee."),

    # ------------------------------------------------ Noord-Holland
    ("amsterdam", "Amsterdam", "Noord-Holland", "Groot-Amsterdam",
     "Amsterdam heeft veel gesloten bouwblokken met hellende voordaken en platte achterdaken, en in de binnenstad vrijwel altijd erfgoedregels."),
    ("amstelveen", "Amstelveen", "Noord-Holland", "Amstelland",
     "Amstelveen bestaat grotendeels uit naoorlogse bouw met veel platte daken en gestapelde woningen."),
    ("uithoorn", "Uithoorn", "Noord-Holland", "Amstelland",
     "Uithoorn ligt aan de Amstel in veenweidegebied, met overwegend naoorlogse woonwijken."),
    ("aalsmeer", "Aalsmeer", "Noord-Holland", "Amstelland",
     "Aalsmeer heeft naast woningbouw veel kassen en bedrijfsgebouwen met grote platte daken."),
    ("diemen", "Diemen", "Noord-Holland", "Groot-Amsterdam",
     "Diemen grenst direct aan Amsterdam en bestaat vooral uit naoorlogse bouw met platte daken."),
    ("weesp", "Weesp", "Noord-Holland", "Gooi",
     "Weesp heeft een beschermde vestingkern met steile daken en daarbuiten naoorlogse wijken."),
    ("naarden", "Naarden", "Noord-Holland", "Gooi",
     "Naarden-Vesting is een beschermd stadsgezicht; voor dakwerk aan panden binnen de vesting gelden aanvullende regels."),
    ("bussum", "Bussum", "Noord-Holland", "Gooi",
     "Bussum telt veel woningen uit het interbellum met complexe dakvormen, dakkapellen en kilgoten."),
    ("hilversum", "Hilversum", "Noord-Holland", "Gooi",
     "Hilversum heeft veel architectonisch bijzondere woningen uit het interbellum, met platte en flauw hellende daken."),
    ("haarlem", "Haarlem", "Noord-Holland", "Kennemerland",
     "Haarlem heeft een beschermde binnenstad met smalle panden en steile daken, naast wijken uit het interbellum."),
    ("heemstede", "Heemstede", "Noord-Holland", "Kennemerland",
     "Heemstede bestaat grotendeels uit villabebouwing uit het interbellum met complexe daken en veel dakdetails."),
    ("zandvoort", "Zandvoort", "Noord-Holland", "Kennemerland",
     "Zandvoort ligt direct aan zee; zout, zand en wind belasten dakbedekking, zinkwerk en bevestigingen sterker dan in het binnenland."),
    ("hoofddorp", "Hoofddorp", "Noord-Holland", "Haarlemmermeer",
     "Hoofddorp ligt in de diepe droogmakerij Haarlemmermeer, in open gebied met veel naoorlogse bebouwing."),
    ("zaandam", "Zaandam", "Noord-Holland", "Zaanstreek",
     "Zaandam heeft veel houten bebouwing en smalle panden in de oude kern, naast naoorlogse wijken."),

    # ------------------------------------------------ Flevoland
    ("almere", "Almere", "Flevoland", "Flevoland",
     "Almere is vanaf 1976 gebouwd, waardoor grote aantallen daken vrijwel gelijktijdig de vervangingsleeftijd naderen."),
    ("zeewolde", "Zeewolde", "Flevoland", "Flevoland",
     "Zeewolde is de jongste gemeente van Nederland en ligt in open polderland met hoge windbelasting op de dakranden."),
]

BY_SLUG = {p[0]: p for p in PLAATSEN}

PROVINCIES = ["Noord-Brabant", "Limburg", "Gelderland", "Utrecht",
              "Zuid-Holland", "Noord-Holland", "Flevoland"]

PROVINCIE_TEKST = {
    "Noord-Brabant": (
        "Noord-Brabant heeft een gespreide bebouwing met veel vrijstaande en halfopen woningen op "
        "zandgrond, en daarnaast een groot aantal agrarische bijgebouwen. Op schuren en stallen van "
        "voor 2001 ligt vaak nog asbesthoudende golfplaat. In de steden gaat het vaker om "
        "vooroorlogse rijwoningen met een hellend voordak en een platte aanbouw achteraan."),
    "Limburg": (
        "In Limburg wisselen historische kernen met steile pannen- en leiendaken af met naoorlogse "
        "uitbreidingen en sterk agrarische gebieden. In Maastricht en de oudere kernen spelen "
        "erfgoedregels bij vrijwel elke wijziging aan het dak."),
    "Gelderland": (
        "Gelderland loopt van open rivierenland tot bosrijke stuwwallen. In de Betuwe en de Liemers "
        "staat de bebouwing open en is de windbelasting hoger; op de Veluwe en de Veluwezoom staan "
        "veel woningen onder hoge bomen, wat het gootonderhoud bepaalt."),
    "Utrecht": (
        "De provincie Utrecht combineert een dichtbebouwde stadsregio met villagebieden op de "
        "Heuvelrug en veenweidegebied in het westen. Op de Heuvelrug gaat het vaak om complexe "
        "dakvormen met kilgoten en dakkapellen, in het veengebied speelt bodemdaling mee."),
    "Zuid-Holland": (
        "Zuid-Holland is de dichtstbebouwde provincie, met veel naoorlogse bouw met platte daken en "
        "vooroorlogse wijken met een hellend voordak en een plat achterdak. Langs de kust komt daar "
        "de belasting van zout en wind bij, in het veenweidegebied de bodemdaling."),
    "Noord-Holland": (
        "Noord-Holland loopt van het duingebied tot het Gooi en de droogmakerijen. Aan de kust "
        "belasten zout en wind het zink- en loodwerk sterker; in het Gooi en Kennemerland gaat het "
        "vaak om villabebouwing uit het interbellum met complexe daken."),
    "Flevoland": (
        "Flevoland is de jongste provincie, met bebouwing die vanaf de jaren zestig in relatief korte "
        "periodes tot stand kwam. Daardoor naderen grote aantallen daken vrijwel gelijktijdig de "
        "vervangingsleeftijd. De open polderligging betekent bovendien een hoge windbelasting."),
}
